In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Define a basic machine translation dataset
source_texts = ['hello', 'how are you', 'goodbye']
target_texts = ['bonjour', 'comment ça va', 'au revoir']

In [ ]:
# source_vocab = set()
# target_vocab = set()
# word = 'hello'
# chars = list(word)
# for i in chars :
#   source_vocab.add(i)
# print(chars)
# print(source_vocab)


In [ ]:
# Create a set of characters for source and target texts

source_vocab,target_vocab = set(),set()

for i in source_texts :
  temp = list(i)
  for j in temp :
    source_vocab.add(j)

for i in target_texts :
  temp = list(i)
  for j in temp :
    target_vocab.add(j)

print(source_vocab)
print(target_vocab)

source_vocab_size = len(source_vocab)
target_vocab_size = len(target_vocab)


{'h', 'a', 'w', ' ', 'u', 'g', 'r', 'd', 'l', 'b', 'e', 'y', 'o'}
{'i', 'j', 'a', 'c', 'm', 't', ' ', 'ç', 'u', 'r', 'n', 'v', 'b', 'e', 'o'}


In [ ]:
# source_char_to_int = {char: idx for idx, char in enumerate(source_vocab)}
# target_char_to_int = {char: idx for idx, char in enumerate(target_vocab)}
# source_int_to_char = {idx: char for char, idx in source_char_to_int.items()}
# target_int_to_char = {idx: char for char, idx in target_char_to_int.items()}

# Initialize dictionaries
source_char_to_int = {}
target_char_to_int = {}
source_int_to_char = {}
target_int_to_char = {}

# Populate source_char_to_int and source_int_to_char
for idx, char in enumerate(source_vocab):
    source_char_to_int[char] = idx
    source_int_to_char[idx] = char

# Populate target_char_to_int and target_int_to_char
for idx, char in enumerate(target_vocab):
    target_char_to_int[char] = idx
    target_int_to_char[idx] = char


In [ ]:
print(source_char_to_int)
print(source_int_to_char)

{'h': 0, 'a': 1, 'w': 2, ' ': 3, 'u': 4, 'g': 5, 'r': 6, 'd': 7, 'l': 8, 'b': 9, 'e': 10, 'y': 11, 'o': 12}
{0: 'h', 1: 'a', 2: 'w', 3: ' ', 4: 'u', 5: 'g', 6: 'r', 7: 'd', 8: 'l', 9: 'b', 10: 'e', 11: 'y', 12: 'o'}


In [ ]:
# Convert text sequences to integer sequences
# Initialize lists
source_sequences = []
target_sequences = []

# Populate source_sequences
for text in source_texts:
    sequence = []
    for char in text:
        sequence.append(source_char_to_int[char])
    source_sequences.append(sequence)

# Populate target_sequences
for text in target_texts:
    sequence = []
    for char in text:
        sequence.append(target_char_to_int[char])
    target_sequences.append(sequence)


In [ ]:
print(type(source_sequences))
print(source_sequences)

<class 'list'>
[[0, 10, 8, 8, 12], [0, 12, 2, 3, 1, 6, 10, 3, 11, 12, 4], [5, 12, 12, 7, 9, 11, 10]]


In [ ]:
# Pad sequences to the same length
max_sequence_length = max(len(seq) for seq in source_sequences)
print(max_sequence_length)
source_sequences = tf.keras.preprocessing.sequence.pad_sequences(source_sequences, maxlen=max_sequence_length, padding='post')
target_sequences = tf.keras.preprocessing.sequence.pad_sequences(target_sequences, maxlen=max_sequence_length, padding='post')

11


In [ ]:
print(source_sequences)
print(type(source_sequences))
print(target_sequences)
print()
print(max_sequence_length)
print(target_vocab_size)

[[ 0 10  8  8 12  0  0  0  0  0  0]
 [ 0 12  2  3  1  6 10  3 11 12  4]
 [ 5 12 12  7  9 11 10  0  0  0  0]]
<class 'numpy.ndarray'>
[[12 14 10  1 14  8  9  0  0  0  0]
 [ 4  4 13 10  5  6  7  2  6 11  2]
 [ 2  8  6  9 13 11 14  0  9  0  0]]

11
15


In [ ]:
# Build the model
input_shape = (max_sequence_length, source_vocab_size)
output_shape = (max_sequence_length, target_vocab_size)

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(source_vocab_size, 64, input_length=max_sequence_length),
    tf.keras.layers.SimpleRNN(128, return_sequences=True),
    tf.keras.layers.Dense(target_vocab_size, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [ ]:
# One-hot encode the target sequences
# target_sequences_one_hot = np.array([tf.keras.utils.to_categorical(seq, num_classes=target_vocab_size) for seq in target_sequences])

target_sequences_one_hot = []

# Iterate over each target sequence in target_sequences
for seq in target_sequences:
    # Perform one-hot encoding on the sequence
    one_hot_seq = tf.keras.utils.to_categorical(seq, num_classes=target_vocab_size)

    # Append the one-hot encoded sequence to the list
    target_sequences_one_hot.append(one_hot_seq)

# Convert the list of one-hot encoded sequences to a NumPy array
target_sequences_one_hot = np.array(target_sequences_one_hot)

In [ ]:
model.fit(source_sequences, target_sequences_one_hot, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 17ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 2/10
1/1 [==============================] - 0s 15ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 3/10
1/1 [==============================] - 0s 14ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 4/10
1/1 [==============================] - 0s 15ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 5/10
1/1 [==============================] - 0s 14ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 6/10
1/1 [==============================] - 0s 14ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 7/10
1/1 [==============================] - 0s 16ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 8/10
1/1 [==============================] - 0s 20ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 9/10
1/1 [==============================] - 0s 21ms/step - loss: 0.0424 - accuracy: 0.9697
Epoch 10/10
1/1 [==============================] - 0s 19ms/step - loss: 0.0424 - accuracy: 0.9697


In [ ]:
# Translate a new input sequence
input_sequence = "how are you"
input_sequence = [source_char_to_int[char] for char in input_sequence]
input_sequence = tf.keras.preprocessing.sequence.pad_sequences([input_sequence], maxlen=max_sequence_length, padding='post')
output_sequence = model.predict(input_sequence)[0]

1/1 [==============================] - 0s 21ms/step


In [ ]:
print(output_sequence)

[[2.3907507e-04 1.5937358e-04 1.4504964e-05 3.6110690e-05 4.9949849e-01
  4.6643036e-05 7.6743192e-05 5.3608092e-05 9.1793263e-05 7.1887931e-05
  1.0749953e-04 9.6581382e-05 4.9945989e-01 2.3631928e-05 2.4235711e-05]
 [1.1592835e-05 1.4065132e-05 7.0454882e-07 1.2726161e-06 9.9925482e-01
  2.0478324e-06 1.2901623e-05 1.8303978e-06 1.6897637e-06 6.5595218e-06
  1.7338008e-06 5.6772046e-06 1.4901564e-04 4.2652291e-06 5.3201517e-04]
 [7.0494507e-06 1.4206194e-05 3.1734178e-06 1.2149198e-05 4.3979035e-06
  2.4491032e-07 2.5369831e-05 2.8119293e-06 6.3504649e-06 2.6484382e-05
  1.6360893e-04 1.1380936e-06 8.8101530e-07 9.9964273e-01 8.9499947e-05]
 [1.5863208e-06 1.0311741e-04 6.4771866e-06 5.1991142e-06 1.2917462e-06
  6.7424194e-06 8.0284593e-08 3.2241191e-05 4.4899738e-07 3.8272323e-05
  9.9975240e-01 2.1639796e-06 4.9110795e-06 4.5098310e-05 1.3297881e-07]
 [1.0285685e-05 4.2576623e-05 7.1787130e-05 1.2629608e-05 2.9837614e-05
  9.9969292e-01 6.3813673e-07 3.3532680e-07 7.0253341e-06 9.

In [ ]:
# Decode the output sequence
output_sequence = [target_int_to_char[np.argmax(char)] for char in output_sequence]

In [ ]:
print(output_sequence)

['m', 'm', 'e', 'n', 't', ' ', 'ç', 'a', ' ', 'v', 'a']


In [ ]:
print("Input Sequence: 'how are you'")
print("Translated Sequence:", ''.join(output_sequence))

Input Sequence: 'how are you'
Translated Sequence: mment ça va
